apiVersion: apps/v1
kind: Deployment
metadata:
  name: contagem-deployment
  labels:
    app: contagem
spec:
  replicas: 4
  selector:
    matchLabels:
      app: contagem
  template:
    metadata:
      labels:
        app: contagem
    spec:
      containers:
      - name: contagem
        image: renatogroffe/apicontagem-3.1-alpine
        env:
          - name: TesteAmbiente
            value: Utilizando o Azure Kubernetes Service (AKS) - Docker Day
        ports:
        - containerPort: 80